version: "3.8"
services:
  back-app:
    container_name: "olla_comun"
    build:
      context: ./backEnd-ollaComun
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9095:9095"
    depends_on:
      - mysql


  front-app:
    container_name: react_app
    build:
      context: ./frontend-ollacomun
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4300:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - back-app

  mysql:
    container_name: "database_mysql"
    image: mysql:8.0.28
    restart: always
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mamitas_db"

