version: '3.8'
services:
  front-app:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4300:80"
    environment:
      - CHOKIDAR_USEPOLLING=true