version: "3.8"
services:
  app:
    container_name: "olla_comun"
    build: .
    restart: always
    ports:
      - "9095:9095"
    depends_on:
      - mysql
#    networks:
#      - red_ollacomun
#    volumes:
#      - ollacomun-data:/var/lib/mysql

  mysql:
    container_name: "database_mysql"
    image: mysql
    restart: always
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mamitas_db"
#    networks:
#      - red_ollacomun
#    volumes:
#      - ollacomun-data:/var/lib/mysql

#networks:
#  red_ollacomun:
#volumes:
#  ollacomun-data:
